# Generated by Django 3.2.18 on 2023-11-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=255)),
                ('a_date', models.DateField()),
                ('a_week', models.CharField(choices=[('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일'), ('토', '토요일'), ('일', '일요일')], max_length=10)),
                ('a_start_time', models.TimeField()),
                ('a_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_category', models.CharField(choices=[('운동', '운동'), ('약속', '약속'), ('여행', '여행'), ('회의', '회의'), ('기타', '기타')], max_length=10)),
                ('s_name', models.CharField(max_length=255)),
                ('s_week', models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금'), ('토', '토'), ('일', '일')], max_length=3)),
                ('s_start_time', models.TimeField()),
                ('s_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=255)),
                ('w_date', models.DateField()),
                ('w_week', models.CharField(choices=[('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일'), ('토', '토요일'), ('일', '일요일')], max_length=10)),
                ('w_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_day', models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금'), ('토', '토'), ('일', '일')], max_length=3)),
                ('st_start_time', models.TimeField()),
                ('st_end_time', models.TimeField()),
                ('st_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='aid.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_day', models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금'), ('토', '토'), ('일', '일')], max_length=3)),
                ('at_start_time', models.TimeField()),
                ('at_end_time', models.TimeField()),
                ('at_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_times', to='aid.assignment')),
            ],
        ),
    ]
