# Generated by Django 3.2.18 on 2023-11-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wm_memo', models.CharField(max_length=255)),
                ('wm_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_memo', to='aid.work')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_memo', models.CharField(max_length=255)),
                ('sm_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_memo', to='aid.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_memo', models.CharField(max_length=255)),
                ('am_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_memo', to='aid.assignment')),
            ],
        ),
    ]
