# Generated by Django 3.2.18 on 2023-11-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_assignmentmemo_schedulememo_workmemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_date', models.DateField()),
                ('c_week', models.CharField(choices=[('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일'), ('토', '토요일'), ('일', '일요일')], max_length=10)),
                ('c_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_memo', models.CharField(max_length=255)),
                ('cm_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memo', to='aid.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_day', models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금'), ('토', '토'), ('일', '일')], max_length=3)),
                ('ct_start_time', models.TimeField()),
                ('ct_end_time', models.TimeField()),
                ('ct_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_times', to='aid.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='workmemo',
            name='wm_work',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='a_end_time',
            new_name='a_deadline',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='a_start_time',
        ),
        migrations.DeleteModel(
            name='AssignmentTime',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='WorkMemo',
        ),
    ]
