# Generated by Django 3.2.18 on 2023-11-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0003_auto_20231124_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmemo',
            name='am_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_memos', to='aid.assignment'),
        ),
        migrations.AlterField(
            model_name='coursememo',
            name='cm_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memos', to='aid.course'),
        ),
        migrations.AlterField(
            model_name='schedulememo',
            name='sm_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_memos', to='aid.schedule'),
        ),
    ]
